In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
data={
      'Name':['Dinesh','Ramesh','Nirpesh','mohan','Hari'],
    'Age':[28,24,35,None,32],
    'City':['New york','Paris','Berlin','Berlin','london']
}
df = pd.DataFrame(data)
df

      Name   Age      City
0   Dinesh  28.0  New york
1   Ramesh  24.0     Paris
2  Nirpesh  35.0    Berlin
3    mohan   NaN    Berlin
4     Hari  32.0    london